GET http://localhost:5000/api/categories?user_uuid=77803c1a-8c1a-492a-89be-f219735b2aef
Accept: application/json

### Create root category

POST http://localhost:5000/api/categories
Accept: application/json
Content-Type: application/json

{
  "name": "New category 1",
  "user_uuid": "77803c1a-8c1a-492a-89be-f219735b2aef"
}

### Create sub category

POST http://localhost:5000/api/categories
Accept: application/json
Content-Type: application/json

{
  "name": "Sub category 1",
  "user_uuid": "77803c1a-8c1a-492a-89be-f219735b2aef",
  "parent_uuid": "85970ed4-37d2-41c9-9353-65ee8264ebdc"
}

### Update category

PATCH http://localhost:5000/api/categories/af20d9e9-c651-4c71-9cc8-7e18c675f87c
Accept: application/json
Content-Type: application/json

{
  "name": "1 sub category",
  "user_uuid": "77803c1a-8c1a-492a-89be-f219735b2aef"
}

### Delete category

DELETE http://localhost:5000/api/categories/85970ed4-37d2-41c9-9353-65ee8264ebdc
Accept: application/json
Content-Type: application/json

{
  "user_uuid": "77803c1a-8c1a-492a-89be-f219735b2aef"
}