GET http://localhost:8083/api/tags?id=1,2,3,4,5,6,7,8,9
Accept: application/json

### Create tag

POST http://localhost:8083/api/tags
Content-Type: application/json

{
  "name": "tag 4",
  "color": "hex",
  "owner_id": "1"
}

### Update tag

PATCH http://localhost:8083/api/tags/1
Content-Type: application/json

{
  "name": "tag 111",
  "color": "sss",
  "owner_id": "1"
}

### Delete tag

DELETE http://localhost:8083/api/tags/1
Content-Type: application/json